#!/bin/bash
# PromptBuddy 发布提醒

echo "================================================"
echo "🎉 PromptBuddy 发布提醒！"
echo "================================================"
echo ""
echo "今天是 2026-03-23，GitHub 账号已满 14 天！"
echo ""
echo "=== 执行发布命令 ==="
echo ""
echo "1. 确认登录状态:"
echo "   clawhub whoami"
echo ""
echo "2. 发布到 ClawHub:"
echo "   cd ~/.openclaw/workspace/skills/promptbuddy"
echo "   clawhub publish . --slug promptbuddy --name 'PromptBuddy' --version 2.2.0"
echo ""
echo "3. 验证发布:"
echo "   clawhub inspect promptbuddy"
echo ""
echo "================================================"
echo "GitHub 仓库: https://github.com/Steventsang18/promptbuddy"
echo "================================================"
